# ==========================================
# SSH Hardening Configuration
# ==========================================

# Moving SSH port into a custom number.
Port 2222

# Disable root login entirely. Use a standard user with sudo.
PermitRootLogin no

# Enforce SSH key-based authentication only. Kill passwords.
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no

# Limit authentication attempts to slow down brute-forcers
MaxAuthTries 3

# Provide specific information in banner messages.
Banner /etc/issue.net